cache:
  - npm
  - directories:
      - ./node_modules/

matrix:
  include:
    - dist: bionic
    - dist: xenial

install:
  - yarn --frozen-lockfile

jobs:
  include:
    - language: node_js
      node_js:
        - 14.9.0
      stage: build
      script:
        - npm run build

deploy:
  - provider: surge
    skip_cleanup: true
    project: ./build/
    domain: https://technikhil314.surge.sh
    on:
      branch: master
      tags: false
